---
- name: "Asegurar que Apache2 está instalado"
  apt:
    pkg: apache2
    state: present
    update_cache: yes
  become: yes

- name: "Copiar plantilla index"
  template: 
    src: index.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  become: yes

- name: "Copiar fichero al servidor remoto"
  copy:
    src: fichero.html
    dest: /var/www/html/fichero.html
    owner: www-data
    group: www-data
    mode: '0644'
  become: yes

- name: "Copiar fichero de configuración y reiniciar el servicio"
  copy:
    src: etc/apache2/ports.conf
    dest: /etc/apache2/ports.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart apache2
  become: yes
